//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAnimeWorld.Seed {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DescriptionData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DescriptionData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyAnimeWorld.Seed.DescriptionData", typeof(DescriptionData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A shinigami, as a god of death, can kill any person—provided they see their victim&apos;s face and write their victim&apos;s name in a notebook called a Death Note. One day, Ryuk, bored by the shinigami lifestyle and interested in seeing how a human would use a Death Note, drops one into the human realm.
        ///
        ///High school student and prodigy Light Yagami stumbles upon the Death Note and—since he deplores the state of the world—tests the deadly notebook by writing a criminal&apos;s name in it. When the criminal dies immediate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Death_Note {
            get {
                return ResourceManager.GetString("Death_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside. Meanwhile in the city, Taki Tachibana lives a busy life as a high school student while juggling his part-time job and hopes for a future in architecture.
        ///
        ///One day, Mitsuha awakens in a room that is not her own and suddenly finds herself living the dream life in Tokyo—but in Taki&apos;s body! Elsewhere, Taki finds himself living Mitsuh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kimi_no_Na_wa {
            get {
                return ResourceManager.GetString("Kimi_no_Na_wa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music accompanies the path of the human metronome, the prodigious pianist Kousei Arima. But after the passing of his mother, Saki Arima, Kousei falls into a downward spiral, rendering him unable to hear the sound of his own piano.
        ///
        ///Two years later, Kousei still avoids the piano, leaving behind his admirers and rivals, and lives a colorless life alongside his friends Tsubaki Sawabe and Ryouta Watari. However, everything changes when he meets a beautiful violinist, Kaori Miyazono, who stirs up his world and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shigatsu_wa_Kimi_no_Uso {
            get {
                return ResourceManager.GetString("Shigatsu_wa_Kimi_no_Uso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the year 2022, virtual reality has progressed by leaps and bounds, and a massive online role-playing game called Sword Art Online (SAO) is launched.
        /// With the aid of &quot;&quot;NerveGear&quot;&quot; technology, players can control their avatars within the game using nothing but their own thoughts.
        ///Kazuto Kirigaya, nicknamed &quot;&quot;Kirito,&quot;&quot; is among the lucky few enthusiasts who get their hands on the first shipment of the game. He logs in to find himself, 
        ///with ten-thousand others, in the scenic and elaborate world of Aincr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sword_Art_Online {
            get {
                return ResourceManager.GetString("Sword_Art_Online", resourceCulture);
            }
        }
    }
}
